<a href="https://colab.research.google.com/github/suchithgali/pytorch_practice/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get tensor back as python int
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1, 2],
                        [3, 4],
                        [6, 7],
                        [4, 3]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 4, 2])

In [ ]:
TENSOR[0]

tensor([[1, 2],
        [3, 4],
        [6, 7],
        [4, 3]])

In [ ]:
random_tensor = torch.rand(6, 5)
random_tensor

tensor([[0.3309, 0.1765, 0.0170, 0.4091, 0.9537],
        [0.8868, 0.0156, 0.8994, 0.9192, 0.6344],
        [0.3938, 0.4122, 0.1026, 0.3859, 0.1429],
        [0.8911, 0.4491, 0.7990, 0.8485, 0.7235],
        [0.4137, 0.0565, 0.2904, 0.9743, 0.1709],
        [0.8130, 0.6794, 0.2188, 0.1705, 0.4844]])

In [ ]:
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [ ]:
zero = torch.zeros(size=(3, 4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
random_tensor.dtype

torch.float32

In [ ]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeroes = torch.zeros_like(input = one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, #data type of the tensor
                                                device=None, # what device is the tensor on
                                                requires_grad=False) #whether or not to track gradients with this tensor's operations
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_32_tensor.dtype

torch.float16

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [ ]:
some_random_tensor = torch.rand(6, 8, dtype=torch.float16, device="cpu")

In [ ]:
print(f"Datatype of tensor: {some_random_tensor.dtype}")
print(f"Shape of tensor: {some_random_tensor.shape}")
print(f"Device tensor is on: {some_random_tensor.device}")

Datatype of tensor: torch.float16
Shape of tensor: torch.Size([6, 8])
Device tensor is on: cpu


In [ ]:
math_tensor = torch.tensor([[1, 2, 3],
                           [3, 4, 5]])
math_tensor + 10

tensor([[11, 12, 13],
        [13, 14, 15]])

In [ ]:
torch.matmul(math_tensor, math_tensor.T)

tensor([[14, 26],
        [26, 50]])

In [ ]:
math_tensor.T

tensor([[1, 3],
        [2, 4],
        [3, 5]])

In [ ]:
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
torch.min(x)

tensor(1)

In [ ]:
x.max()

tensor(90)

In [ ]:
torch.mean(x, dtype = torch.float32) #requires a tensor of float32 to work

tensor(45.)

In [ ]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [ ]:
x.argmin() #finding the min position (returns index position)

tensor(0)

In [ ]:
import torch
x = torch.arange(1., 13.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [ ]:
x_reshaped = x.reshape(1, 12) #has to be compatible with original dimensions
x_reshaped, x_reshaped.shape

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]))

In [ ]:
z = x.view(1, 12)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]))

In [ ]:
z[:, 0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]))

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.],
        [11., 11., 11., 11.],
        [12., 12., 12., 12.]])

In [ ]:
x_reshaped.squeeze() #removes all the single dimensions

tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([12])

In [ ]:
x_unsqueeze = x_reshaped.unsqueeze(dim = 2) #adds a dimension at position dim

In [ ]:
x_unsqueeze.shape

torch.Size([1, 12, 1])

In [ ]:
x_original = torch.rand(size=(224, 224, 3))
x_permuted = x_original.permute(2, 0, 1) #shifts axis 0->1, 1->2, 2->0, permute is a view
x_permuted.shape

torch.Size([3, 224, 224])

In [ ]:
import torch
x_indexing = torch.arange(1, 10).reshape(1, 3, 3)
x_indexing, x_indexing.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x_indexing[0][0]

tensor([1, 2, 3])

In [ ]:
x_indexing[:, 0]

tensor([[1, 2, 3]])

In [ ]:
x_indexing[:, 1, 1]

tensor([5])

In [ ]:
x_indexing[0, 0, :]

tensor([1, 2, 3])

In [ ]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
import torch

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)


In [ ]:
import torch

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

random_tensor_C, random_tensor_D

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]))

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
tensor_cpu = torch.tensor([1, 2, 3], device = "cpu")

print(tensor_cpu, tensor_cpu.device)

tensor([1, 2, 3]) cpu


In [ ]:
tensor_on_gpu = tensor_cpu.to(device) #to gpu
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
tensor_on_gpu.numpy() #can't convert tensor on gpu to numpy, have to put on cpu first

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
tensor_cpu = tensor_cpu.cpu().numpy()
tensor_cpu, tensor_cpu.device

(array([1, 2, 3]), 'cpu')

In [ ]:
!nvidia-smi

Mon Feb 16 01:13:16 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA L4                      Off |   00000000:00:03.0 Off |                    0 |
| N/A   64C    P0             31W /   72W |     196MiB /  23034MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
import torch

RANDOM_SEED = 7

random = torch.rand(1, 1, 1, 10)
random_new = random.squeeze()
random_new, random_new.shape

(tensor([0.4189, 0.0655, 0.8839, 0.8083, 0.7528, 0.8988, 0.6839, 0.7658, 0.9149,
         0.3993]),
 torch.Size([10]))