<a href="https://colab.research.google.com/github/suchithgali/pytorch_practice/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get tensor back as python int
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1, 2],
                        [3, 4],
                        [6, 7],
                        [4, 3]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 4, 2])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]])

In [ ]:
random_tensor = torch.rand(6, 5)
random_tensor

tensor([[0.6603, 0.2217, 0.6134, 0.0851, 0.6381],
        [0.6028, 0.9760, 0.4744, 0.1173, 0.7109],
        [0.4672, 0.2356, 0.4607, 0.7221, 0.1277],
        [0.6955, 0.2802, 0.1027, 0.6848, 0.8351],
        [0.2446, 0.0323, 0.5180, 0.1496, 0.5755],
        [0.9182, 0.4469, 0.9963, 0.7402, 0.6641]])

In [ ]:
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)