<a href="https://colab.research.google.com/github/suchithgali/pytorch_practice/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get tensor back as python int
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1, 2],
                        [3, 4],
                        [6, 7],
                        [4, 3]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 4, 2])

In [ ]:
TENSOR[0]

tensor([[1, 2],
        [3, 4],
        [6, 7],
        [4, 3]])

In [ ]:
random_tensor = torch.rand(6, 5)
random_tensor

tensor([[0.3309, 0.1765, 0.0170, 0.4091, 0.9537],
        [0.8868, 0.0156, 0.8994, 0.9192, 0.6344],
        [0.3938, 0.4122, 0.1026, 0.3859, 0.1429],
        [0.8911, 0.4491, 0.7990, 0.8485, 0.7235],
        [0.4137, 0.0565, 0.2904, 0.9743, 0.1709],
        [0.8130, 0.6794, 0.2188, 0.1705, 0.4844]])

In [ ]:
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [ ]:
zero = torch.zeros(size=(3, 4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
random_tensor.dtype

torch.float32

In [ ]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeroes = torch.zeros_like(input = one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, #data type of the tensor
                                                device=None, # what device is the tensor on
                                                requires_grad=False) #whether or not to track gradients with this tensor's operations
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_32_tensor.dtype

torch.float16

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [ ]:
some_random_tensor = torch.rand(6, 8, dtype=torch.float16, device="cpu")

In [ ]:
print(f"Datatype of tensor: {some_random_tensor.dtype}")
print(f"Shape of tensor: {some_random_tensor.shape}")
print(f"Device tensor is on: {some_random_tensor.device}")

Datatype of tensor: torch.float16
Shape of tensor: torch.Size([6, 8])
Device tensor is on: cpu


In [ ]:
math_tensor = torch.tensor([[1, 2, 3],
                           [3, 4, 5]])
math_tensor + 10

tensor([[11, 12, 13],
        [13, 14, 15]])

In [ ]:
torch.matmul(math_tensor, math_tensor.T)

tensor([[14, 26],
        [26, 50]])

In [ ]:
math_tensor.T

tensor([[1, 3],
        [2, 4],
        [3, 5]])

In [13]:
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [15]:
torch.min(x)

tensor(1)

In [ ]:
x.max()

tensor(90)

In [ ]:
torch.mean(x, dtype = torch.float32) #requires a tensor of float32 to work

tensor(45.)

In [ ]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [14]:
x.argmin() #finding the min position (returns index position)

tensor(0)

In [25]:
import torch
x = torch.arange(1., 13.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [38]:
x_reshaped = x.reshape(1, 12) #has to be compatible with original dimensions
x_reshaped, x_reshaped.shape

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]))

In [29]:
z = x.view(1, 12)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]))

In [32]:
z[:, 0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]))

In [34]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.],
        [11., 11., 11., 11.],
        [12., 12., 12., 12.]])

In [39]:
x_reshaped.squeeze() #removes all the single dimensions

tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [40]:
x_reshaped.squeeze().shape

torch.Size([12])

In [50]:
x_unsqueeze = x_reshaped.unsqueeze(dim = 2)

In [51]:
x_unsqueeze.shape

torch.Size([1, 12, 1])